name: "Releaser Linter"
description: "Checks PR titles for semantic correctness"

inputs:
  github-token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Semantic PR Title Lint
      uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
