name: DCO/CLA Verification
on:
  pull_request:
  push:
  workflow_call:
jobs:
  dco-cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: check required actions
        uses: actions/github-script@v7
        id: check_required_actions
        with:
          script: |
            if(!context.payload.repository.license) {
              return;
            }

            core.setOutput('dco_required', context.payload.repository.license.key == 'apache-2')

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python 3.x
        if: steps.check_required_actions.outputs.dco_required
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.x'
      - name: Check DCO
        if: steps.check_required_actions.outputs.dco_required
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DCO_CHECK_VERBOSE: '1'
          DCO_CHECK_EXCLUDE_PATTERN: '@(block.xyz|squareup.com|cash.app)$'
          DCO_CHECK_EXCLUDE_EMAILS: 29139614+renovate[bot]@users.noreply.github.com
        run: |
          pip3 install -U dco-check
          dco-check