on:
  push:
    paths:
      - external-contributor-legal-checks/**
      - .github/workflows/external-contributor-legal-checks-build.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.24.x"
      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9
      - run: |
          KO_DOCKER_REPO=ghcr.io/block/ospo/external-contributor-legal-checks ko build
        working-directory: external-contributor-legal-checks
